

export const CLASSES_REQUEST = 'CLASSES_REQUEST';
export const CLASSES_SUCCESS = 'CLASSES_SUCCESS';
export const CLASSES_FAILED = 'CLASSES_FAILED';
export const RESET = 'RESET';
export const FILTER_CLASSES = 'FILTER_CLASSES';
export const FILTER_CLASSES_SUCCESS = 'FILTER_CLASSES_SUCCESS';

